apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  #Especifica que esta solicitud se enlazará directamente al volumen host-pv
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      #Indica que el pod necesita 1 GiB de almacenamiento, que es exactamente lo que ofrece el host-pv.
      storage: 1Gi