apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  #Define un volumen que se encuentra en el nodo del clúster, con una capacidad de almacenamiento de 1 GiB.
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    #Especifica que el volumen está basado en un directorio local en el nodo anfitrión, en la ruta /data.
    path: /data
    #Si el directorio no existe, Kubernetes lo creará automáticamente
    type: DirectoryOrCreate