apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    app: storage-pod
spec:
  containers:
    - name: storage-container
      image: eduard2diaz/greet:storage
      ports:
        - containerPort: 8080
      env:
        - name: FILE_SAVE_PATH
          value: "/mnt/data" # Ruta donde se montará el volumen
      #Monta el volumen asociado en el contenedor bajo la ruta /mnt/data
      volumeMounts:
        - mountPath: "/mnt/data"
          name: storage-volume
  volumes:
    #Asocia el pod con el PersistentVolumeClaim llamado host-pvc
    - name: storage-volume
      persistentVolumeClaim:
        #indica el volum claim a utilizar
        claimName: host-pvc