apiVersion: v1
kind: ReplicationController
metadata:
  #nombre del replication controller
  name: greet-rc
spec:
  replicas: 3
  selector:
    #selector del pod
    app: greet
  #plantilla del pod
  template:
    metadata:
      labels:
        app: greet
    spec:
      containers:
        - name: greet
          image: eduard2diaz/greet:storage
          ports:
            - containerPort: 8080