apiVersion: v1
kind: Pod
metadata:
  name: greet-pod
  labels:
    app: greet
spec:
  containers:
    - name: greet
      image: eduard2diaz/greet:storage
      livenessProbe:
        httpGet:
          #ruta a donde hacer la solicitud
          path: /
          #puerto al que hay que conectarse para hacer la prueba, es donde la app esta corriendo
          port: 8080
        # Kubernetes will wait 15 seconds before executing the first probe.
        initialDelaySeconds: 15