apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet
  template:
    metadata:
      labels:
        app: greet
    spec:
      containers:
        - name: greet
          image: eduard2diaz/greet:storage
          env:
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  #indicamos el secreto a utilizar
                  name: mi-secret
                  #indicamos la llave del secreto a utilizar
                  key: usuario