apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  type: NodePort
  ports:
    - port: 80        # Puerto expuesto por el Servicio
      targetPort: 8080 # Redirige al puerto 8080 del contenedor
      nodePort: 30080 # Puerto fijo en el nodo (opcional, rango 30000-32767)
  selector:
    app: greet