apiVersion: v1
kind: Service
metadata:
  name: greet-service
spec:
  #sessionAffinity puede tener 2 valores (None o ClientIP). Pero si usamos ClientIP cada vez que un usuario haga una
  #solicitud, usando la misma ip de cliente, sera redirigido al mismo pod. Es similar a un sticky session
  sessionAffinity: ClientIP
  selector: 
    app: greet
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: NodePort