apiVersion: v1
kind: Pod
metadata:
  name: greet-pod
  labels:
    app: greet
spec:
  #Indicamos el service account a utilizar el pod
  serviceAccountName: my-service-account
  containers:
    - name: greet
      image: eduard2diaz/greet:storage
