apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    app: storage-pod
spec:
  containers:
    - name: storage-container
      image: eduard2diaz/greet:storage
      ports:
        - containerPort: 8080
      env:
        - name: FILE_SAVE_PATH
          value: "/mnt/data" # Ruta donde se montará el volumen
      volumeMounts:
        #Especifica dónde estará disponible el volumen dentro del contenedor.
        - mountPath: "/mnt/data" # Punto de montaje dentro del contenedor
          name: storage-volume
  volumes:
    - name: storage-volume
      #Proporciona la ruta real dentro del pod donde se guardara el contenido
      hostPath:
        path: /data
        type: DirectoryOrCreate