version: '3.8'

services:
  config-server-1:
    build:
      context: .
      dockerfile: Dockerfile_no_env
    ports:
      - "8083:8080"

  config-server-2:
    build:
      context: .
      dockerfile: Dockerfile_no_env
    ports:
      - "8084:8080"
    environment:
      - APP_NAME=COMPOSER_2

  config-server-3:
    build:
      context: .
      dockerfile: Dockerfile_with_env
    ports:
      - "8085:8080"

  config-server-4:
    build:
      context: .
      dockerfile: Dockerfile_with_env
    ports:
      - "8086:8080"
    environment:
      - APP_NAME=COMPOSER_4
