apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet
  template:
    metadata:
      labels:
        app: greet
    spec:
      containers:
        - name: greet
          image: eduard2diaz/greet:storage
          env:
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  name: mi-secret
                  key: usuario
          volumeMounts:
            - name: secret-vol
              #se indica donde se montara el volumen
              mountPath: "/etc/secrets" # Ruta donde estará disponible el secreto
              readOnly: true
      volumes:
        - name: secret-vol
          secret:
            #Se agrega una referencia al secreto llamado mi-secret
            secretName: mi-secret